import { OrderHistoryItem, OrderStatus } from '../orderHistoryItem';

export const MOCK_PURCHASES: OrderHistoryItem[] = [
  {
    id: 1,
    buyer: {
      id: 1,
      username: 'buyer1',
      profileImageUrl: 'imageKey1',
    },
    seller: {
      id: 1,
      username: 'seller1',
      profileImageUrl: 'imageKey1',
    },
    status: OrderStatus.PENDING,
    product: {
      id: 1,
      name: 'Product 1',
      sellerId: 1,
      category: 'test',
      condition: 'test',
      shippingPrice: 0,
      createdAt: new Date().toISOString(),
      quantity: 1,
      description: 'Description 1',
      price: 10,
      imageUrls: ['imageKey1'],
    },
    createdAt: new Date().toISOString(),
    finalPrice: 10,
    shippingDate: new Date().toISOString(),
    deliveredDate: new Date().toISOString(),
  },
  {
    id: 2,
    buyer: {
      id: 1,
      username: 'buyer1',
      profileImageUrl: 'imageKey1',
    },
    seller: {
      id: 1,
      username: 'seller1',
      profileImageUrl: 'imageKey1',
    },
    status: OrderStatus.SHIPPED,
    product: {
      id: 2,
      name: 'Product 2',
      sellerId: 1,
      category: 'test',
      condition: 'test',
      shippingPrice: 0,
      createdAt: new Date().toISOString(),
      quantity: 1,
      description: 'Description 2',
      price: 20,
      imageUrls: ['imageKey2'],
    },
    createdAt: new Date().toISOString(),
    finalPrice: 20,
    shippingDate: new Date().toISOString(),
    deliveredDate: new Date().toISOString(),
  },
  {
    id: 3,
    buyer: {
      id: 1,
      username: 'buyer1',
      profileImageUrl: 'imageKey1',
    },
    seller: {
      id: 1,
      username: 'seller1',
      profileImageUrl: 'imageKey1',
    },
    status: OrderStatus.DELIVERED,
    product: {
      id: 3,
      name: 'Product 3',
      sellerId: 1,
      category: 'test',
      condition: 'test',
      shippingPrice: 0,
      createdAt: new Date().toISOString(),
      quantity: 1,
      description: 'Description 3',
      price: 30,
      imageUrls: ['imageKey3'],
    },
    createdAt: new Date().toISOString(),
    finalPrice: 30,
    shippingDate: new Date().toISOString(),
    deliveredDate: new Date().toISOString(),
  },
];

export const MOCK_SALES: OrderHistoryItem[] = [
  {
    id: 4,
    buyer: {
      id: 1,
      username: 'buyer1',
      profileImageUrl: 'imageKey1',
    },
    seller: {
      id: 1,
      username: 'seller1',
      profileImageUrl: 'imageKey1',
    },
    status: OrderStatus.PENDING,
    product: {
      id: 1,
      name: 'Product 1',
      sellerId: 1,
      category: 'test',
      condition: 'test',
      shippingPrice: 0,
      createdAt: new Date().toISOString(),
      quantity: 1,
      description: 'Description 1',
      price: 10,
      imageUrls: ['imageKey1'],
    },
    createdAt: new Date().toISOString(),
    finalPrice: 10,
    shippingDate: new Date().toISOString(),
    deliveredDate: new Date().toISOString(),
  },
  {
    id: 5,
    buyer: {
      id: 1,
      username: 'buyer1',
      profileImageUrl: 'imageKey1',
    },
    seller: {
      id: 1,
      username: 'seller1',
      profileImageUrl: 'imageKey1',
    },
    status: OrderStatus.SHIPPED,
    product: {
      id: 2,
      name: 'Product 2',
      sellerId: 1,
      category: 'test',
      condition: 'test',
      shippingPrice: 0,
      createdAt: new Date().toISOString(),
      quantity: 1,
      description: 'Description 2',
      price: 20,
      imageUrls: ['imageKey2'],
    },
    createdAt: new Date().toISOString(),
    finalPrice: 20,
    shippingDate: new Date().toISOString(),
    deliveredDate: new Date().toISOString(),
  },
];
